version: '3'
services:
  app: 
    container_name: desafio-rits-docker
    restart: always
    build: .
    ports:
      - '8000:8000'
    command: php artisan serve --host=localhost --port=8000
    links:
      - postgres
  postgres:
    container_name: desafio-database
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
